### PR TITLE
MGDCTRS-1793 : Allowing Pod/Containers resource metrics to display in Dataplane Operator Dashboard

### PR DESCRIPTION
**Pull request by rpancham**
## Description
Adding the following metrics to observatorium 
1.kube_pod_info
2.kube_pod_container_resource_requests
3.container_memory_working_set_bytes
4.kube_pod_container_resource_limits
5.kube_pod_container_resource_requests
6.container_network_receive_bytes_total
7.container_network_receive_packets_dropped_total
8.container_network_receive_packets_total
9.container_network_receive_errors_total

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Verified independently by reviewer
- [ ] Required Standard Operating Procedure (SOP) is added.

## Prometheus

- [ ] Changes were tested against dev environment

## Grafana

- [ ] You have imported the changes into a dev or staging environment

### CODE REVIEW

**Review by lgarciaaco — APPROVED** [review]

**Review by shivamG640 — APPROVED** [review]

**Review by lgarciaaco — CHANGES_REQUESTED** [review]
What is this change about? Can you please provide a title and a description that match what this PR is doing?

**Review by lgarciaaco — COMMENTED** [review]
Also maybe squash the commits

**Comment by rpancham** [comment]
> Also maybe squash the commits

Yes squashed the previous commit

**Review by lgarciaaco — APPROVED** [review]

**Comment by rpancham** [comment]
I will follow up this changes in new PR

**Pull request closed without merging**
